---
# tasks file for deployment
- name: Deploy Avi Controller1
  deploy_controller:
    ovftool_path: '{{ ovftool_path }}'
    vcenter_host: '{{ item.vcenter_host }}'
    vcenter_user: '{{ vcenter_user }}'
    vcenter_password: '{{ vcenter_password }}'
    con_datacenter: '{{ datacenter }}'
    con_cluster: '{{ cluster }}'
    con_mgmt_network: '{{ mgmt_network }}'
    con_ova_path: '{{ ova_path }}'
    con_power_on: '{{ power_on }}'
    con_vcenter_folder: '{{ vcenter_folder }}'
    state: '{{ state }}'
    con_vm_name: '{{ item.name }}'
    con_mgmt_ip: '{{ item.mgmt_ip }}'
    con_mgmt_mask: '{{ item.mgmt_mask}}'
    con_default_gw: '{{ item.default_gw }}'
  with_items:
   - "{{ controllers }}"
- pause: minutes=3
