avi_config:
  serviceenginegroup:
    - name: Default-Group
      cloud_ref: '/api/cloud?name=Default-Cloud'
      vcenter_folder: rwhitt
      vcenter_clusters:
        cluster_refs:
          - '/api/vimgrclusterruntime?name=Arista'
        include: True
      max_se: 4
      buffer_se: 1
      se_name_prefix: rwhitt
    
  network:
    - name: "PG-988"
      #cloud_ref: '/api/cloud?name=Default-Cloud'
      avi_api_update_method: PUT
      vcenter_dvs: false
      dhcp_enabled: false
      configured_subnets:
        - prefix:
            ip_addr:
              addr: 10.90.88.0
              type: 'V4'
            mask: 24
          static_ranges:
          - begin:
              addr: 10.90.88.246
              type: 'V4'
            end:
              addr: 10.90.88.250
              type: 'V4'
  
  avi_cloud_discovery_wait: 1          
  cloud:
    - name: Default-Cloud
      vtype: CLOUD_VCENTER
      dhcp_enabled: false
      license_type: 'LIC_CORES'
      vcenter_configuration:
        username: '{{ vcenter.username }}'
        password: '{{ vcenter.password }}'
        datacenter: '{{ vcenter.datacenter }}'
        vcenter_dvs: false
        privilege: 'WRITE_ACCESS'
        vcenter_url: '{{ vcenter.vcenter_url }}'
        management_network: "/api/vimgrnwruntime?name=PG-988"
        management_ip_subnet:
          ip_addr: 
            addr: 10.90.88.1
            type: V4
          mask: 24
