avi_config:
  avi_cloud_discovery_wait: 450
  cloud:
    - name: Default-Cloud
      vtype: CLOUD_VCENTER
      dhcp_enabled: true
      license_type: LIC_CORES
      vcenter_configuration:
        username: administrator@mitchchen.com
        password: h6j5?HxL3zlSO$
        datacenter: DC1
        management_network: VM Network
        privilege: WRITE_ACCESS
        vcenter_url: 192.168.38.20

  serviceenginegroup:
    - name: Default-Group
      cloud_ref: /api/cloud?name=Default-Cloud
      vcenter_folder: ge
      vcenter_clusters:
        cluster_refs:
          - /api/vimgrclusterruntime?name=Arista
        include: True
      max_se: 4
      buffer_se: 1
      se_name_prefix: grastogi


  systemconfiguration:
    - email_configuration:
        smtp_type: SMTP_LOCAL_HOST
        from_email: admin@avicontroller.net
      global_tenant_config:
        se_in_provider_context: true
        tenant_access_to_provider_se: true
        tenant_vrf: false
      ntp_servers:
        - server:
            type: DNS
            addr: 0.us.pool.ntp.org
        - server:
            type: DNS
            addr: 0.us.pool.ntp.org
        - server:
            type: DNS
            addr: 0.us.pool.ntp.org
        - server:
            type: DNS
            addr: 0.us.pool.ntp.org
      portal_configuration:
        allow_basic_authentication: false
        disable_remote_cli_shell: false
        enable_clickjacking_protection: true
        enable_http: true
        enable_https: true
        password_strength_check: false
        redirect_to_https: true
        sslkeyandcertificate_refs:
          - "/api/sslkeyandcertificate?name=System-Default-Portal-Cert"
          - "/api/sslkeyandcertificate?name=System-Default-Portal-Cert-EC256"
        sslprofile_ref: /api/sslprofile?name=System-Standard-Portal
        use_uuid_from_input: false

