---
# vars file for deployement
ovftool_path: /usr/lib/vmware-ovftool
vcenter_user: 'administrator@mitchchen.com'
vcenter_password: 'h6j5?HxL3zlSO$'
vcenter_folder: ge
datacenter: DC1
cluster: MyCluster1
mgmt_network: VM Network
ova_path: /home/ge/controller-17.2.13-9168.ova
power_on: true
number_of_cpus: 8
memory: 24
controllers:
  - name: AviController1
    vcenter_host: 192.168.38.20
    mgmt_ip: 192.168.38.71
    mgmt_mask: 255.255.255.0
    default_gw: 192.168.38.1
  - name: AviController2
    vcenter_host: 192.168.38.20
    mgmt_ip: 192.168.38.72
    mgmt_mask: 255.255.255.0
    default_gw: 192.168.38.1
  - name: AviController3
    vcenter_host: 192.168.38.20
    mgmt_ip: 192.168.38.73
    mgmt_mask: 255.255.255.0
    default_gw: 192.168.38.1
