- hosts: localhost
  connection: local
  vars:
    config: sysconfig
    avi_config_file: ../config/administration/{{ config }}
    avi_creds_file: ../credentials
  roles:
    - role: avinetworks.avisdk
    - role: avinetworks.aviconfig
  gather_facts: no
