- hosts: localhost
  connection: local
  vars:
    avi_config_file: ../config/system/administration
    avi_creds_file: ../credentials
  roles:
    - role: avinetworks.avisdk
    - role: avinetworks.aviconfig
  gather_facts: no
