- hosts: control
  vars:
    avi_config_file: ../config/infrastructure/{{ cloud }}
    avi_creds_file: ../credentials
  roles:
    - role: avinetworks.avisdk
    - role: avinetworks.aviconfig
  gather_facts: no
