- hosts: localhost
  name: Setting admin password
  vars_files:
    - ../credentials
  tasks:
    - name: Set admin password
      avi_useraccount:
        avi_credentials: '{{ avi_credentials }}'
        old_password: '{{ old_password }}'
        api_version: '{{ avi_credentials.api_version }}'
  roles:
    - role: avinetworks.avisdk 
  gather_facts: no
  ignore_errors: yes
