avi_config:
  pool:
    - name: ext-pool-A
      lb_algorithm: LB_ALGORITHM_ROUND_ROBIN
      servers:
        - ip:
             addr: 192.168.38.3
             type: 'V4'
    - name: ext-pool-B
      lb_algorithm: LB_ALGORITHM_LEAST_CONNECTIONS
      health_monitor_refs:
        - '/api/healthmonitor?name=ext-hm'
        - '/api/healthmonitor?name=ext_multiline_hm'
        - '/api/healthmonitor?name=ext-hm-tcp-ecv'

      servers:
        - ip:
             addr: 192.168.38.1
             type: 'V4'

  healthmonitor:
    - name: ext-hm
      http_monitor:
        http_request: "HEAD / HTTP/1.0"
        http_response_code:
          - HTTP_2XX
          - HTTP_3XX
      receive_timeout: 4
      failed_checks: 3
      send_interval: 10
      successful_checks: 3
      type: HEALTH_MONITOR_HTTP

    - name: ext-hm-tcp-ecv
      receive_timeout: 4
      failed_checks: 2
      monitor_port: 22222
      send_interval: 10
      successful_checks: 2
      type: HEALTH_MONITOR_TCP
      tcp_monitor:
        tcp_half_open: false
        tcp_response: "ECV Control: In"
        tcp_request: "GET / \r\n HTTP/1.0\r\n\r\n"

    - name: ext_multiline_hm
      failed_checks: 1
      https_monitor: '{"http_request": "GET /index.html HTTP/1.1", "\r\nConnection": "Close", "\r\nhttp_response_code": ["HTTP_2XX", "HTTP_3XX"], "type": "HEALTH_MONITOR_HTTP"}'

  httppolicyset:
    - name: ext-httppolicy
      http_request_policy:
        rules:
          - index: 1
            enable: true
            name: "ext-pool-A"
            match:
              path:
                match_case: INSENSITIVE
                match_str:
                  - /foo
                match_criteria: EQUALS
            switching_action:
              action: HTTP_SWITCHING_SELECT_POOL
              status_code: HTTP_LOCAL_RESPONSE_STATUS_CODE_200
              pool_ref: "/api/pool?name=ext-pool-A"
          - index: 2
            enable: true
            name: "ext-pool-B"
            match:
              path:
                match_case: INSENSITIVE
                match_str:
                  - /bar
                match_criteria: CONTAINS
            switching_action:
              action: HTTP_SWITCHING_SELECT_POOL
              status_code: HTTP_LOCAL_RESPONSE_STATUS_CODE_200
              pool_ref: "/api/pool?name=ext-pool-B"
      is_internal_policy: false

  virtualservice:
    - name: extensive
      services:
        - port: 80
      pool_ref: '/api/pool?name=ext-pool-A'
      vip:
        - ip_address:
            addr: 192.168.38.92
            type: 'V4'
          vip_id: '1'
      cloud_ref: '/api/cloud?name=Default-Cloud'
      ssl_key_and_certificate_refs:
        - '/api/sslkeyandcertificate?name=ext-cert'
      ssl_profile_ref: '/api/sslprofile?name=System-Standard'
      application_profile_ref: '/api/applicationprofile?name=System-Secure-HTTP'
      services:
        - port: 80
        - port: 443
          enable_ssl: true
      http_policies:
        - index: 11
          http_policy_set_ref: '/api/httppolicyset?name=ext-httppolicy'

  sslkeyandcertificate:
    - name: ext-cert
      key: {{ lookup('file', '{{ playbook_dir }}/../../config/ssl/ext-cert.key') }}
      certificate:
        self_signed: true
        certificate: {{ lookup('file', '{{ playbook_dir }}/../../config/ssl/ext-cert.crt')}}
      type: SSL_CERTIFICATE_TYPE_VIRTUALSERVICE

