# VS Config
vs_name: prakash_vs
vip: 192.168.38.80
certs: [System-Default-Cert-EC, System-Default-Cert]
vs_ports:
  - port: 80
  - port: 8080
  - port: 443
    enable_ssl: true


# Pool config    
algorithm: LB_ALGORITHM_ROUND_ROBIN
pool_name: prakash_pool
pool_members: [192.168.38.3, 192.168.38.4, 192.168.38.5] 
server_port: 8080
health_monitors: [System-Ping]
   
