---
ovftool_path: /usr/lib/vmware-ovftool
datacenter: DC1
cluster: MyCluster1
mgmt_network: VM Network
ova_path: /home/ge/controller-17.2.13-9168.ova
power_on: true
vcenter_folder: ge
number_of_cpus: 8
memory: 24
controllers:
  - name: AviController1
    vcenter_host: 192.168.38.20
    mgmt_ip: 192.168.38.71
    mgmt_mask: 255.255.255.0
    default_gw: 192.168.38.1
  #- name: 
  #  vcenter_host: 
  #  mgmt_ip: 
  #  mgmt_mask: 
  #  default_gw: 
  #- name: 
  #  vcenter_host: 
  #  mgmt_ip: 
  #  mgmt_mask: 
  #  default_gw: 
